% ---------- solve odes  -----------
%y(1+6i) -- ux
%y(2+6i) -- dux/dt
%y(3+6i) -- uy
%y(4+6i) -- duy/dt
%y(5+6i) -- theta
%y(6+6i) -- dtheta/dt
function dy = ODEsNorm(T,y)
% global parameters
global theta0 vol
global Nx Ny N damp Ndamp
global alfa
global K_theta K_s
global T_out theta_out Ux_out Uy_out
global theta_st ex_st
global Mm Bm

Theta0 = theta0+theta_st;

% initialize solution
dy = zeros(6*N,1);
j = 1;
i = 1:Ny;
posi = 6*((i-1)*Nx+j-1); % the left column units

%% boundary conditions: apply impact to first unit
    % obtain input data from theoretical solutions
Dispx = interp1(T_out,Ux_out,T);
Dispy = interp1(T_out,Uy_out,T);
Theta = interp1(T_out,theta_out,T);
if isnan(Dispx)
    Dispx = Ux_out(end);
end
if isnan(Dispy)
    Dispy = Uy_out(end);
end
if isnan(Theta)
    Theta = theta_out(end);
end
% apply solutions on first unit
y(posi+5) = Theta;
y(posi+6) = 0;
y(posi+1) = Dispx;
y(posi+2) = 0;
y(posi+3) = Dispy;
y(posi+4) = 0;
%% equations of the chain
for j=2:Nx-1
    for i=1 % down side free boundary
        % define positions
        posi = 6*((i-1)*Nx+j-1); % [i,j]-th unit
        left_posi = 6*((i-1)*Nx+(j-1)-1); % [i,j-1]-th unit
        right_posi = 6*((i-1)*Nx+(j+1)-1); % [i,j+1]-th unit
        up_posi = 6*((i+1-1)*Nx+j-1); % [i+1,j]-th unit
        % (1) equations of x displacement conponent
        dy(posi+1) = y(posi+2);
        dy(posi+2) = ((y(right_posi+1)+y(left_posi+1)-2*y(posi+1)) ...
            +K_s*(y(up_posi+1)-y(posi+1)) ...
            -1/2/cos(theta0)*(cos(y(right_posi+5)+Theta0)-cos(y(left_posi+5)+Theta0)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(up_posi+5)+Theta0)-sin(y(posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^4*(3*cos(y(posi+5)-y(right_posi+5))+sin(y(posi+5)+y(right_posi+5)+2*Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^4*(3*cos(y(left_posi+5)-y(posi+5))+sin(y(left_posi+5)+y(posi+5)+2*Theta0))) ...
            -damp*y(posi+2);
        % (2) equations of y displacement conponent
        dy(posi+3) = y(posi+4);
        dy(posi+4) = ((1+ex_st+y(up_posi+3)-y(posi+3)) ...
            +K_s*(y(right_posi+3)+y(left_posi+3)-2*y(posi+3)) ...
            -1/2/cos(theta0)*(cos(y(up_posi+5)+Theta0)+cos(y(posi+5)+Theta0)) ...
            -(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(right_posi+5)+Theta0)-sin(y(left_posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^4*(-3*cos(y(posi+5)-y(up_posi+5))+sin(y(posi+5)+y(up_posi+5)+2*Theta0))) ...
            -damp*y(posi+4);
        % (3) equations of rotation
        dy(posi+5) = y(posi+6);
        dy(posi+6) = alfa^2*(-K_theta*(y(up_posi+5)+y(right_posi+5)+y(left_posi+5)+3*y(posi+5)+6*theta_st) ...
            -1/2/cos(theta0)*sin(y(posi+5)+Theta0)*(3*(1+ex_st)+y(right_posi+1)-y(left_posi+1)+y(up_posi+3)-y(posi+3)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*cos(y(posi+5)+Theta0)*(y(up_posi+1)-y(posi+1)-y(right_posi+3)+y(left_posi+3)) ...
            +1/4/cos(theta0)^2*sin(y(posi+5)+Theta0)*(cos(y(right_posi+5)+Theta0)+cos(y(left_posi+5)+Theta0)+cos(y(up_posi+5)+Theta0)+3*cos(y(posi+5)+Theta0)) ...
            +K_s/4/cos(theta0)^2*cos(y(posi+5)+Theta0)*(sin(y(right_posi+5)+Theta0)+sin(y(left_posi+5)+Theta0)+sin(y(up_posi+5)+Theta0)-3*sin(y(posi+5)+Theta0)) ...
            -Mm*vol*Bm*cos(pi/4+y(posi+5)+Theta0) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^3*(cos(y(posi+5)+y(right_posi+5)+2*Theta0)-3*sin(y(posi+5)-y(right_posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^3*(cos(y(left_posi+5)+y(posi+5)+2*Theta0)+3*sin(y(left_posi+5)-y(posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^3*(cos(y(posi+5)+y(up_posi+5)+2*Theta0)+3*sin(y(posi+5)-y(up_posi+5)))) ...
            -damp*y(posi+6);
    end
    for i=2:Ndamp 
        % define positions
        posi = 6*((i-1)*Nx+j-1); % [i,j]-th unit
        left_posi = 6*((i-1)*Nx+(j-1)-1); % [i,j-1]-th unit
        right_posi = 6*((i-1)*Nx+(j+1)-1); % [i,j+1]-th unit
        up_posi = 6*((i+1-1)*Nx+j-1); % [i+1,j]-th unit
        down_posi = 6*((i-1-1)*Nx+j-1); % [i-1,j]-th unit
        % (1) equations of x displacement conponent
        dy(posi+1) = y(posi+2);
        dy(posi+2) = ((y(right_posi+1)+y(left_posi+1)-2*y(posi+1)) ...
            +K_s*(y(up_posi+1)+y(down_posi+1)-2*y(posi+1)) ...
            -1/2/cos(theta0)*(cos(y(right_posi+5)+Theta0)-cos(y(left_posi+5)+Theta0)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(up_posi+5)+Theta0)-sin(y(down_posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^4*(3*cos(y(posi+5)-y(right_posi+5))+sin(y(posi+5)+y(right_posi+5)+2*Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^4*(3*cos(y(left_posi+5)-y(posi+5))+sin(y(left_posi+5)+y(posi+5)+2*Theta0))) ...
            -damp/Ndamp.^2*(Ndamp-i+1).^2*y(posi+2);
        % (2) equations of y displacement conponent
        dy(posi+3) = y(posi+4);
        dy(posi+4) = ((y(up_posi+3)+y(down_posi+3)-2*y(posi+3)) ...
            +K_s*(y(right_posi+3)+y(left_posi+3)-2*y(posi+3)) ...
            -1/2/cos(theta0)*(cos(y(up_posi+5)+Theta0)-cos(y(down_posi+5)+Theta0)) ...
            -(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(right_posi+5)+Theta0)-sin(y(left_posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^4*(-3*cos(y(posi+5)-y(up_posi+5))+sin(y(posi+5)+y(up_posi+5)+2*Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^4*(-3*cos(y(down_posi+5)-y(posi+5))+sin(y(down_posi+5)+y(posi+5)+2*Theta0))) ...
            -damp/Ndamp.^2*(Ndamp-i+1).^2*y(posi+4);
        % (3) equations of rotation
        dy(posi+5) = y(posi+6);
        dy(posi+6) = alfa^2*(-K_theta*(y(up_posi+5)+y(down_posi+5)+y(right_posi+5)+y(left_posi+5)+4*y(posi+5)+8*theta_st) ...
            -1/2/cos(theta0)*sin(y(posi+5)+Theta0)*(4*(1+ex_st)+y(right_posi+1)-y(left_posi+1)+y(up_posi+3)-y(down_posi+3)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*cos(y(posi+5)+Theta0)*(y(up_posi+1)-y(down_posi+1)-y(right_posi+3)+y(left_posi+3)) ...
            +1/4/cos(theta0)^2*sin(y(posi+5)+Theta0)*(cos(y(up_posi+5)+Theta0)+cos(y(down_posi+5)+Theta0)+cos(y(right_posi+5)+Theta0)+cos(y(left_posi+5)+Theta0)+4*cos(y(posi+5)+Theta0)) ...
            +K_s/4/cos(theta0)^2*cos(y(posi+5)+Theta0)*(sin(y(up_posi+5)+Theta0)+sin(y(down_posi+5)+Theta0)+sin(y(right_posi+5)+Theta0)+sin(y(left_posi+5)+Theta0)-4*sin(y(posi+5)+Theta0)) ...
            -Mm*vol*Bm*cos(pi/4+y(posi+5)+Theta0) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^3*(cos(y(posi+5)+y(right_posi+5)+2*Theta0)-3*sin(y(posi+5)-y(right_posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^3*(cos(y(left_posi+5)+y(posi+5)+2*Theta0)+3*sin(y(left_posi+5)-y(posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^3*(cos(y(posi+5)+y(up_posi+5)+2*Theta0)+3*sin(y(posi+5)-y(up_posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^3*(cos(y(down_posi+5)+y(posi+5)+2*Theta0)-3*sin(y(down_posi+5)-y(posi+5)))) ...
            -damp/Ndamp.^2*(Ndamp-i+1).^2*y(posi+6);
    end
    for i=Ndamp+1:Ny-Ndamp 
        % define positions
        posi = 6*((i-1)*Nx+j-1); % [i,j]-th unit
        left_posi = 6*((i-1)*Nx+(j-1)-1); % [i,j-1]-th unit
        right_posi = 6*((i-1)*Nx+(j+1)-1); % [i,j+1]-th unit
        up_posi = 6*((i+1-1)*Nx+j-1); % [i+1,j]-th unit
        down_posi = 6*((i-1-1)*Nx+j-1); % [i-1,j]-th unit
        % (1) equations of x displacement conponent
        dy(posi+1) = y(posi+2);
        dy(posi+2) = ((y(right_posi+1)+y(left_posi+1)-2*y(posi+1)) ...
            +K_s*(y(up_posi+1)+y(down_posi+1)-2*y(posi+1)) ...
            -1/2/cos(theta0)*(cos(y(right_posi+5)+Theta0)-cos(y(left_posi+5)+Theta0)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(up_posi+5)+Theta0)-sin(y(down_posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^4*(3*cos(y(posi+5)-y(right_posi+5))+sin(y(posi+5)+y(right_posi+5)+2*Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^4*(3*cos(y(left_posi+5)-y(posi+5))+sin(y(left_posi+5)+y(posi+5)+2*Theta0)));
        % (2) equations of y displacement conponent
        dy(posi+3) = y(posi+4);
        dy(posi+4) = ((y(up_posi+3)+y(down_posi+3)-2*y(posi+3)) ...
            +K_s*(y(right_posi+3)+y(left_posi+3)-2*y(posi+3)) ...
            -1/2/cos(theta0)*(cos(y(up_posi+5)+Theta0)-cos(y(down_posi+5)+Theta0)) ...
            -(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(right_posi+5)+Theta0)-sin(y(left_posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^4*(-3*cos(y(posi+5)-y(up_posi+5))+sin(y(posi+5)+y(up_posi+5)+2*Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^4*(-3*cos(y(down_posi+5)-y(posi+5))+sin(y(down_posi+5)+y(posi+5)+2*Theta0)));
        % (3) equations of rotation
        dy(posi+5) = y(posi+6);
        dy(posi+6) = alfa^2*(-K_theta*(y(up_posi+5)+y(down_posi+5)+y(right_posi+5)+y(left_posi+5)+4*y(posi+5)+8*theta_st) ...
            -1/2/cos(theta0)*sin(y(posi+5)+Theta0)*(4*(1+ex_st)+y(right_posi+1)-y(left_posi+1)+y(up_posi+3)-y(down_posi+3)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*cos(y(posi+5)+Theta0)*(y(up_posi+1)-y(down_posi+1)-y(right_posi+3)+y(left_posi+3)) ...
            +1/4/cos(theta0)^2*sin(y(posi+5)+Theta0)*(cos(y(up_posi+5)+Theta0)+cos(y(down_posi+5)+Theta0)+cos(y(right_posi+5)+Theta0)+cos(y(left_posi+5)+Theta0)+4*cos(y(posi+5)+Theta0)) ...
            +K_s/4/cos(theta0)^2*cos(y(posi+5)+Theta0)*(sin(y(up_posi+5)+Theta0)+sin(y(down_posi+5)+Theta0)+sin(y(right_posi+5)+Theta0)+sin(y(left_posi+5)+Theta0)-4*sin(y(posi+5)+Theta0)) ...
            -Mm*vol*Bm*cos(pi/4+y(posi+5)+Theta0) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^3*(cos(y(posi+5)+y(right_posi+5)+2*Theta0)-3*sin(y(posi+5)-y(right_posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^3*(cos(y(left_posi+5)+y(posi+5)+2*Theta0)+3*sin(y(left_posi+5)-y(posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^3*(cos(y(posi+5)+y(up_posi+5)+2*Theta0)+3*sin(y(posi+5)-y(up_posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^3*(cos(y(down_posi+5)+y(posi+5)+2*Theta0)-3*sin(y(down_posi+5)-y(posi+5))));
    end
    for i=Ny-Ndamp+1:Ny-1 
        % define positions
        posi = 6*((i-1)*Nx+j-1); % [i,j]-th unit
        left_posi = 6*((i-1)*Nx+(j-1)-1); % [i,j-1]-th unit
        right_posi = 6*((i-1)*Nx+(j+1)-1); % [i,j+1]-th unit
        up_posi = 6*((i+1-1)*Nx+j-1); % [i+1,j]-th unit
        down_posi = 6*((i-1-1)*Nx+j-1); % [i-1,j]-th unit
        % (1) equations of x displacement conponent
        dy(posi+1) = y(posi+2);
        dy(posi+2) = ((y(right_posi+1)+y(left_posi+1)-2*y(posi+1)) ...
            +K_s*(y(up_posi+1)+y(down_posi+1)-2*y(posi+1)) ...
            -1/2/cos(theta0)*(cos(y(right_posi+5)+Theta0)-cos(y(left_posi+5)+Theta0)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(up_posi+5)+Theta0)-sin(y(down_posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^4*(3*cos(y(posi+5)-y(right_posi+5))+sin(y(posi+5)+y(right_posi+5)+2*Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^4*(3*cos(y(left_posi+5)-y(posi+5))+sin(y(left_posi+5)+y(posi+5)+2*Theta0))) ...
            -damp/Ndamp.^2*(i-Ny+Ndamp).^2*y(posi+2);
        % (2) equations of y displacement conponent
        dy(posi+3) = y(posi+4);
        dy(posi+4) = ((y(up_posi+3)+y(down_posi+3)-2*y(posi+3)) ...
            +K_s*(y(right_posi+3)+y(left_posi+3)-2*y(posi+3)) ...
            -1/2/cos(theta0)*(cos(y(up_posi+5)+Theta0)-cos(y(down_posi+5)+Theta0)) ...
            -(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(right_posi+5)+Theta0)-sin(y(left_posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^4*(-3*cos(y(posi+5)-y(up_posi+5))+sin(y(posi+5)+y(up_posi+5)+2*Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^4*(-3*cos(y(down_posi+5)-y(posi+5))+sin(y(down_posi+5)+y(posi+5)+2*Theta0))) ...
            -damp/Ndamp.^2*(i-Ny+Ndamp).^2*y(posi+4);
        % (3) equations of rotation
        dy(posi+5) = y(posi+6);
        dy(posi+6) = alfa^2*(-K_theta*(y(up_posi+5)+y(down_posi+5)+y(right_posi+5)+y(left_posi+5)+4*y(posi+5)+8*theta_st) ...
            -1/2/cos(theta0)*sin(y(posi+5)+Theta0)*(4*(1+ex_st)+y(right_posi+1)-y(left_posi+1)+y(up_posi+3)-y(down_posi+3)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*cos(y(posi+5)+Theta0)*(y(up_posi+1)-y(down_posi+1)-y(right_posi+3)+y(left_posi+3)) ...
            +1/4/cos(theta0)^2*sin(y(posi+5)+Theta0)*(cos(y(up_posi+5)+Theta0)+cos(y(down_posi+5)+Theta0)+cos(y(right_posi+5)+Theta0)+cos(y(left_posi+5)+Theta0)+4*cos(y(posi+5)+Theta0)) ...
            +K_s/4/cos(theta0)^2*cos(y(posi+5)+Theta0)*(sin(y(up_posi+5)+Theta0)+sin(y(down_posi+5)+Theta0)+sin(y(right_posi+5)+Theta0)+sin(y(left_posi+5)+Theta0)-4*sin(y(posi+5)+Theta0)) ...
            -Mm*vol*Bm*cos(pi/4+y(posi+5)+Theta0) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^3*(cos(y(posi+5)+y(right_posi+5)+2*Theta0)-3*sin(y(posi+5)-y(right_posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^3*(cos(y(left_posi+5)+y(posi+5)+2*Theta0)+3*sin(y(left_posi+5)-y(posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^3*(cos(y(posi+5)+y(up_posi+5)+2*Theta0)+3*sin(y(posi+5)-y(up_posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^3*(cos(y(down_posi+5)+y(posi+5)+2*Theta0)-3*sin(y(down_posi+5)-y(posi+5)))) ...
            -damp/Ndamp.^2*(i-Ny+Ndamp).^2*y(posi+6);
    end
    for i=Ny % up side free boudnary
        % define positions
        posi = 6*((i-1)*Nx+j-1); % [i,j]-th unit
        left_posi = 6*((i-1)*Nx+(j-1)-1); % [i,j-1]-th unit
        right_posi = 6*((i-1)*Nx+(j+1)-1); % [i,j+1]-th unit
        down_posi = 6*((i-1-1)*Nx+j-1); % [i-1,j]-th unit
        % (1) equations of x displacement conponent
        dy(posi+1) = y(posi+2);
        dy(posi+2) = ((y(right_posi+1)+y(left_posi+1)-2*y(posi+1)) ...
            +K_s*(y(down_posi+1)-y(posi+1)) ...
            -1/2/cos(theta0)*(cos(y(right_posi+5)+Theta0)-cos(y(left_posi+5)+Theta0)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*(-sin(y(down_posi+5)+Theta0)+sin(y(posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^4*(3*cos(y(posi+5)-y(right_posi+5))+sin(y(posi+5)+y(right_posi+5)+2*Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^4*(3*cos(y(left_posi+5)-y(posi+5))+sin(y(left_posi+5)+y(posi+5)+2*Theta0))) ...
            -damp*y(posi+2);
        % (2) equations of y displacement conponent
        dy(posi+3) = y(posi+4);
        dy(posi+4) = (-(1+ex_st-y(down_posi+3)+y(posi+3)) ...
            +K_s*(y(right_posi+3)+y(left_posi+3)-2*y(posi+3)) ...
            +1/2/cos(theta0)*(cos(y(down_posi+5)+Theta0)+cos(y(posi+5)+Theta0)) ...
            -(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(right_posi+5)+Theta0)-sin(y(left_posi+5)+Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^4*(-3*cos(y(down_posi+5)-y(posi+5))+sin(y(down_posi+5)+y(posi+5)+2*Theta0))) ...
            -damp*y(posi+4);
        % (3) equations of rotation
        dy(posi+5) = y(posi+6);
        dy(posi+6) = alfa^2*(-K_theta*(y(down_posi+5)+y(right_posi+5)+y(left_posi+5)+3*y(posi+5)+6*theta_st) ...
            -1/2/cos(theta0)*sin(y(posi+5)+Theta0)*(3*(1+ex_st)+y(right_posi+1)-y(left_posi+1)+y(posi+3)-y(down_posi+3)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*cos(y(posi+5)+Theta0)*(y(posi+1)-y(down_posi+1)-y(right_posi+3)+y(left_posi+3)) ...
            +1/4/cos(theta0)^2*sin(y(posi+5)+Theta0)*(cos(y(right_posi+5)+Theta0)+cos(y(left_posi+5)+Theta0)+cos(y(down_posi+5)+Theta0)+3*cos(y(posi+5)+Theta0)) ...
            +K_s/4/cos(theta0)^2*cos(y(posi+5)+Theta0)*(sin(y(right_posi+5)+Theta0)+sin(y(left_posi+5)+Theta0)+sin(y(down_posi+5)+Theta0)-3*sin(y(posi+5)+Theta0)) ...
            -Mm*vol*Bm*cos(pi/4+y(posi+5)+Theta0) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(right_posi+1)-y(posi+1))^3*(cos(y(posi+5)+y(right_posi+5)+2*Theta0)-3*sin(y(posi+5)-y(right_posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^3*(cos(y(left_posi+5)+y(posi+5)+2*Theta0)+3*sin(y(left_posi+5)-y(posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^3*(cos(y(down_posi+5)+y(posi+5)+2*Theta0)-3*sin(y(down_posi+5)-y(posi+5)))) ...
            -damp*y(posi+6);
    end
end
for j=Nx % right side free boudnary
    for i=1 
        % define positions
        posi = 6*((i-1)*Nx+j-1); % [i,j]-th unit
        left_posi = 6*((i-1)*Nx+(j-1)-1); % [i,j-1]-th unit
        up_posi = 6*((i+1-1)*Nx+j-1); % [i+1,j]-th unit
        % (1) equations of x displacement conponent
        dy(posi+1) = y(posi+2);
        dy(posi+2) = (-(1+ex_st+y(posi+1)-y(left_posi+1)) ...
            +K_s*(y(up_posi+1)-y(posi+1)) ...
            +1/2/cos(theta0)*(cos(y(left_posi+5)+Theta0)+cos(y(posi+5)+Theta0)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(up_posi+5)+Theta0)-sin(y(posi+5)+Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^4*(3*cos(y(left_posi+5)-y(posi+5))+sin(y(left_posi+5)+y(posi+5)+2*Theta0)));
        % (2) equations of y displacement conponent
        dy(posi+3) = y(posi+4);
        dy(posi+4) = ((1+ex_st+y(up_posi+3)-y(posi+3)) ...
            +K_s*(y(left_posi+3)-y(posi+3)) ...
            -1/2/cos(theta0)*(cos(y(posi+5)+Theta0)+cos(y(up_posi+5)+Theta0)) ...
            -(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(posi+5)+Theta0)-sin(y(left_posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^4*(-3*cos(y(posi+5)-y(up_posi+5))+sin(y(posi+5)+y(up_posi+5)+2*Theta0)));
        % (3) equations of rotation
        dy(posi+5) = y(posi+6);
        dy(posi+6) = alfa^2*(-K_theta*(y(up_posi+5)+y(left_posi+5)+2*y(posi+5)+4*theta_st) ...
            -1/2/cos(theta0)*sin(y(posi+5)+Theta0)*(2*(1+ex_st)+y(posi+1)-y(left_posi+1)+y(up_posi+3)-y(posi+3)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*cos(y(posi+5)+Theta0)*(y(up_posi+1)-y(posi+1)+y(left_posi+3)-y(posi+3)) ...
            +1/4/cos(theta0)^2*sin(y(posi+5)+Theta0)*(cos(y(up_posi+5)+Theta0)+cos(y(left_posi+5)+Theta0)+2*cos(y(posi+5)+Theta0)) ...
            +K_s/4/cos(theta0)^2*cos(y(posi+5)+Theta0)*(sin(y(up_posi+5)+Theta0)+sin(y(left_posi+5)+Theta0)-2*sin(y(posi+5)+Theta0)) ...
            -Mm*Bm*vol*cos(pi/4+y(posi+5)+Theta0) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^3*(cos(y(left_posi+5)+y(posi+5)+2*Theta0)+3*sin(y(left_posi+5)-y(posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^3*(cos(y(posi+5)+y(up_posi+5)+2*Theta0)+3*sin(y(posi+5)-y(up_posi+5))));
    end
    for i=2:Ny-1 
        % define positions
        posi = 6*((i-1)*Nx+j-1); % [i,j]-th unit
        left_posi = 6*((i-1)*Nx+(j-1)-1); % [i,j-1]-th unit
        up_posi = 6*((i+1-1)*Nx+j-1); % [i+1,j]-th unit
        down_posi = 6*((i-1-1)*Nx+j-1); % [i-1,j]-th unit
        % (1) equations of x displacement conponent
        dy(posi+1) = y(posi+2);
        dy(posi+2) = (-(1+ex_st+y(posi+1)-y(left_posi+1)) ...
            +K_s*(y(up_posi+1)+y(down_posi+1)-2*y(posi+1)) ...
            +1/2/cos(theta0)*(cos(y(left_posi+5)+Theta0)+cos(y(posi+5)+Theta0)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(up_posi+5)+Theta0)-sin(y(down_posi+5)+Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^4*(3*cos(y(left_posi+5)-y(posi+5))+sin(y(left_posi+5)+y(posi+5)+2*Theta0)));
        % (2) equations of y displacement conponent
        dy(posi+3) = y(posi+4);
        dy(posi+4) = ((y(up_posi+3)+y(down_posi+3)-2*y(posi+3)) ...
            +K_s*(y(left_posi+3)-y(posi+3)) ...
            -1/2/cos(theta0)*(cos(y(up_posi+5)+Theta0)-cos(y(down_posi+5)+Theta0)) ...
            -(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(posi+5)+Theta0)-sin(y(left_posi+5)+Theta0)) ...
            +3*Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^4*(-3*cos(y(posi+5)-y(up_posi+5))+sin(y(posi+5)+y(up_posi+5)+2*Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^4*(-3*cos(y(down_posi+5)-y(posi+5))+sin(y(down_posi+5)+y(posi+5)+2*Theta0)));
        % (3) equations of rotation
        dy(posi+5) = y(posi+6);
        dy(posi+6) = alfa^2*(-K_theta*(y(left_posi+5)+y(up_posi+5)+y(down_posi+5)+3*y(posi+5)+6*theta_st) ...
            -1/2/cos(theta0)*sin(y(posi+5)+Theta0)*(3*(1+ex_st)+y(posi+1)-y(left_posi+1)+y(up_posi+3)-y(down_posi+3)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*cos(y(posi+5)+Theta0)*(y(up_posi+1)-y(down_posi+1)-y(posi+3)+y(left_posi+3)) ...
            +1/4/cos(theta0)^2*sin(y(posi+5)+Theta0)*(cos(y(left_posi+5)+Theta0)+cos(y(up_posi+5)+Theta0)+cos(y(down_posi+5)+Theta0)+3*cos(y(posi+5)+Theta0)) ...
            +K_s/4/cos(theta0)^2*cos(y(posi+5)+Theta0)*(sin(y(left_posi+5)+Theta0)+sin(y(up_posi+5)+Theta0)+sin(y(down_posi+5)+Theta0)-3*sin(y(posi+5)+Theta0)) ...
            -Mm*Bm*vol*cos(pi/4+y(posi+5)+Theta0) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^3*(cos(y(left_posi+5)+y(posi+5)+2*Theta0)+3*sin(y(left_posi+5)-y(posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(up_posi+3)-y(posi+3))^3*(cos(y(posi+5)+y(up_posi+5)+2*Theta0)+3*sin(y(posi+5)-y(up_posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^3*(cos(y(down_posi+5)+y(posi+5)+2*Theta0)-3*sin(y(down_posi+5)-y(posi+5))));
    end
    for i=Ny 
        % define positions
        posi = 6*((i-1)*Nx+j-1); % [i,j]-th unit
        left_posi = 6*((i-1)*Nx+(j-1)-1); % [i,j-1]-th unit
        down_posi = 6*((i-1-1)*Nx+j-1); % [i-1,j]-th unit
        % (1) equations of x displacement conponent
        dy(posi+1) = y(posi+2);
        dy(posi+2) = (-(1+ex_st+y(posi+1)-y(left_posi+1)) ...
            +K_s*(y(down_posi+1)-y(posi+1)) ...
            +1/2/cos(theta0)*(cos(y(left_posi+5)+Theta0)+cos(y(posi+5)+Theta0)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(posi+5)+Theta0)-sin(y(down_posi+5)+Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^4*(3*cos(y(left_posi+5)-y(posi+5))+sin(y(left_posi+5)+y(posi+5)+2*Theta0)));
        % (2) equations of y displacement conponent
        dy(posi+3) = y(posi+4);
        dy(posi+4) = (-(1+ex_st-y(down_posi+3)+y(posi+3)) ...
            +K_s*(y(left_posi+3)-y(posi+3)) ...
            +1/2/cos(theta0)*(cos(y(down_posi+5)+Theta0)+cos(y(posi+5)+Theta0)) ...
            -(-1)^(i+j)*K_s/2/cos(theta0)*(sin(y(posi+5)+Theta0)-sin(y(left_posi+5)+Theta0)) ...
            -3*Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^4*(-3*cos(y(down_posi+5)-y(posi+5))+sin(y(down_posi+5)+y(posi+5)+2*Theta0)));
        % (3) equations of rotation    
        dy(posi+5) = y(posi+6);
        dy(posi+6) = alfa^2*(-K_theta*(y(left_posi+5)+y(down_posi+5)+2*y(posi+5)+4*theta_st) ...
            -1/2/cos(theta0)*sin(y(posi+5)+Theta0)*(2*(1+ex_st)+y(posi+1)-y(left_posi+1)+y(posi+3)-y(down_posi+3)) ...
            +(-1)^(i+j)*K_s/2/cos(theta0)*cos(y(posi+5)+Theta0)*(y(posi+1)-y(down_posi+1)-y(posi+3)+y(left_posi+3)) ...
            +1/4/cos(theta0)^2*sin(y(posi+5)+Theta0)*(cos(y(left_posi+5)+Theta0)+cos(y(down_posi+5)+Theta0)+2*cos(y(posi+5)+Theta0)) ...
            +K_s/4/cos(theta0)^2*cos(y(posi+5)+Theta0)*(sin(y(left_posi+5)+Theta0)+sin(y(down_posi+5)+Theta0)-2*sin(y(posi+5)+Theta0)) ...
            -Mm*Bm*vol*cos(pi/4+y(posi+5)+Theta0) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+1)-y(left_posi+1))^3*(cos(y(left_posi+5)+y(posi+5)+2*Theta0)+3*sin(y(left_posi+5)-y(posi+5))) ...
            +Mm^2*vol^2/8/pi/(1+ex_st+y(posi+3)-y(down_posi+3))^3*(cos(y(down_posi+5)+y(posi+5)+2*Theta0)-3*sin(y(down_posi+5)-y(posi+5))));
    end

end